### ISSUE TITLE
Crash on clients.py when searching for a player

### ISSUE THREAD

**Issue by felipemoran** [EthanC/CallofDuty.py#30]
When running the example from `README.md` the library crashes. It seems that the function `SearchPlayers` from `Client` class is expecting a return of type dictionary from the function `SearchPlayers` from `HTTP` class but a string is being returned instead and thus getting a value with the key `data` isn't possible. 

```
Traceback (most recent call last):
  File "/path/to/project/bot/playground.py", line 10, in main
    results = await client.SearchPlayers(Platform.Activision, "Captain Price", limit=3)
  File "/path/to/project/venv3.8/lib/python3.8/site-packages/callofduty/client.py", line 551, in SearchPlayers
    data: dict = (await self.http.SearchPlayer(platform.value, username))["data"]
TypeError: string indices must be integers
```

The value being returned by `self.http.SearchPlayer(platform.value, username)` is
```
'{"status":"success","data":[{"platform":"uno","username":"captain price","accountId":"10976285","avatar":null},{"platform":"uno","username":"Captain Price#1183498","accountId":"1324429271582812843","avatar":null},{"platform":"uno","username":"Captain Price#1894839","accountId":"1324684011875463063","avatar":null},{"platform":"uno","username":"Captain Price#2049033","accountId":"8890642","avatar":null},{"platform":"uno","username":"Captain Price#2051998","accountId":"4862470","avatar":null},{"platform":"uno","username":"Captain Price#2737932","accountId":"17897478","avatar":null},{"platform":"uno","username":"Captain Price#3877870","accountId":"17258425793960667868","avatar":null},{"platform":"uno","username":"Captain Price#4186334","accountId":"12959940","avatar":null},{"platform":"uno","username":"Captain Price#4201762","accountId":"1324370735821307157","avatar":null},{"platform":"uno","username":"Captain Price#4862224","accountId":"14700140","avatar":null},{"platform":"uno","username":"Captain Price#5121243","accountId":"20537284","avatar":null},{"platform":"uno","username":"Captain Price#5290091","accountId":"16571244","avatar":null},{"platform":"uno","username":"Captain Price#5922773","accountId":"1324883696992576368","avatar":null},{"platform":"uno","username":"Captain Price#6234889","accountId":"19114688","avatar":null},{"platform":"uno","username":"Captain Price#6670917","accountId":"12107540","avatar":null},{"platform":"uno","username":"Captain Price#7489986","accountId":"19548698","avatar":null},{"platform":"uno","username":"Captain Price#8556707","accountId":"7466647","avatar":null},{"platform":"uno","username":"Captain Price#8720947","accountId":"18787540","avatar":null},{"platform":"uno","username":"Captain Price#8954774","accountId":"15911924","avatar":null},{"platform":"uno","username":"Captain Price#9140400","accountId":"17566006","avatar":null},{"platform":"uno","username":"Captain Price#9270875","accountId":"4318036","avatar":null}]}'
```

System info: 
- MacOS 10.15.4
- Python 3.8 (installed via Homebrew) with clean virtual environment

**Comment by tyeoneill** [comment]
Same issue

**Comment by felipemoran** [comment]
It seems that changing line 27 from `http.py` from
```
if res.headers["Content-Type"].lower() == "application/json;charset=utf-8":
```
to 
```
if res.headers["Content-Type"].lower() == "application/json":
```
solves the issue, but I don't know what are the drawbacks of this modification.

**Comment by tyeoneill** [comment]
> It seems that changing line 27 from `http.py` from
> 
> ```
> if res.headers["Content-Type"].lower() == "application/json;charset=utf-8":
> ```
> 
> to
> 
> ```
> if res.headers["Content-Type"].lower() == "application/json":
> ```
> 
> solves the issue, but I don't know what are the drawbacks of this modification.

I spotted this solution amongst the pull requests, seems to be working fine for me so far.

**Comment by felipemoran** [comment]
True, I'm closing this. #28 fixes the problem
