### ISSUE TITLE
Warzone match details gets 404 

### ISSUE THREAD

**Issue by EdoardoPedrotti** [EthanC/CallofDuty.py#33]
### Summary

If I try to get the details of a Warzone match I get this a 404  and an error

### Reproduction Steps

This is my code:
```
   client = await callofduty.Login(
        os.environ["ATVI_EMAIL"], os.environ["ATVI_PASSWORD"]
    )
    platform = Platform.PlayStation

    title = Title.ModernWarfare

    mode = Mode.Warzone

    matches = await client.GetPlayerMatches(platform=platform, title=title, mode=mode, username="edobounce")

    print(matches)

    match_details = await matches[0].details()

    print(matches)
```
### Expected Results

Details from the Warzone match.

### Actual Results

```
Traceback (most recent call last):
  File "/Users/edoardopedrotti/PycharmProjects/CallofDuty.py/test.py", line 25, in main
    match_details = await matches[0].details()
  File "/Users/edoardopedrotti/PycharmProjects/CallofDuty.py/callofduty/match.py", line 58, in details
    return await self._client.GetMatchDetails(self.title, self.platform, self.id)
  File "/Users/edoardopedrotti/PycharmProjects/CallofDuty.py/callofduty/client.py", line 799, in GetMatchDetails
    return (await self.http.GetMatch(title.value, platform.value, matchId))["data"]
  File "/Users/edoardopedrotti/PycharmProjects/CallofDuty.py/callofduty/http.py", line 263, in GetMatch
    return await self.Send(
  File "/Users/edoardopedrotti/PycharmProjects/CallofDuty.py/callofduty/http.py", line 113, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 200 - The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: DBD552424A508E1D; S3 Extended Request ID: st37DHPW1CXLiS8egWUCLGDaX56g+cY0HKsG5/pu0py/m+ce4D7x4VlaQrUhYorsvKI8nfsfG0c=)

```

### Checklist

-   [x] I have searched the open Issues for duplicates
-   [x] I have shown the entire traceback, if possible
-   [x] I have removed my token from display, if visible

**Comment by EdoardoPedrotti** [comment]
I could not figure out why I am getting this error. if there is a solutions just give me a hint and I will be happy to work on in and make a PR.

**Comment by EthanC** [comment]
The Call of Duty API endpoint for match details does not support Warzone at the moment.

Throwing a unique exception for this isn't consistent with the design of the library, hence the presence of an HTTPException.
