### ISSUE TITLE
Not authenticated despite i have inserted my password and email

### ISSUE THREAD

**Issue by Ste29** [EthanC/CallofDuty.py#62]
### Reproduction Steps

It's the code from the readme
```
import asyncio

import callofduty
from callofduty import Mode, Platform, Title


async def main():
    client = await callofduty.Login("YourEmail@email.com", "YourPassword")

    results = await client.SearchPlayers(Platform.Activision, "Captain Price", limit=3)
    for player in results:
        print(f"{player.username} ({player.platform.name})")

    me = results[1]
    profile = await me.profile(Title.ModernWarfare, Mode.Multiplayer)

    level = profile["level"]
    kd = profile["lifetime"]["all"]["properties"]["kdRatio"]
    wl = profile["lifetime"]["all"]["properties"]["wlRatio"]

    print(f"\n{me.username} ({me.platform.name})")
    print(f"Level: {level}, K/D Ratio: {kd}, W/L Ratio: {wl}")

asyncio.get_event_loop().run_until_complete(main())

```
### Actual Results

```
Traceback (most recent call last):
  File "<input>", line 24, in <module>
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "<input>", line 15, in main
  File "C:\Users\Stefano\Desktop\cod_39\lib\site-packages\callofduty\player.py", line 62, in profile
    return await self._client.GetPlayerProfile(
  File "C:\Users\Stefano\Desktop\cod_39\lib\site-packages\callofduty\client.py", line 595, in GetPlayerProfile
    await self.http.GetPlayerProfile(
  File "C:\Users\Stefano\Desktop\cod_39\lib\site-packages\callofduty\http.py", line 219, in GetPlayerProfile
    return await self.Send(
  File "C:\Users\Stefano\Desktop\cod_39\lib\site-packages\callofduty\http.py", line 113, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 200 - Not permitted: not allowed
```

### Checklist

-   [x] I have searched the open Issues for duplicates
-   [x] I have shown the entire traceback, if possible
-   [x] I have removed my token from display, if visible

### System Information

callofduty.py version 1.2.2

**Comment by Grreg** [comment]
+1 Had the same issue for "AddFriend"

**Comment by EthanC** [comment]
This is not an authentication issue. As the exception message states, you are not permitted to get the profile for the chosen player - it's a privacy settings issue, not relevant to this project.
